### ISSUE TITLE
minio process isn't running 

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#126]
**Description**
However the s3 installation was running successfully, The minio process has been not started inside the container. 

**steps**
- Install s3, succeed
- Make sure that the minio vm has been installed and joined the zt, succeed
- Try to access minio, failed 
- List the minio container process, should find the minio process, failed.

**More information**
- Here is the minio vm running containers 
```python
In [4]: node = j.clients.zos.get('minio_vm', data={'host':'172.28.15.58'})
In [19]: node.client.container.list()
Out[19]: 
{'1': {'cpu': 0.05519314077702066,
  'rss': 7794688,
  'vms': 300244992,
  'swap': 0,
  'container': {'arguments': {'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-robot-autostart-development.flist',
    'mount': {'/var/cache/zrobot/config': '/opt/code/local/stdorg/config',
     '/var/cache/zrobot/data': '/opt/var/data/zrobot/zrobot_data',
     '/var/cache/zrobot/jsconfig': '/root/jumpscale/cfg',
     '/var/cache/zrobot/ssh': '/root/.ssh',
     '/var/run/redis.sock': '/tmp/redis.sock'},
    'host_network': False,
    'identity': '',
    'nics': [{'type': 'default',
      'id': '',
      'hwaddr': '',
      'config': {'dhcp': False, 'cidr': '', 'gateway': '', 'dns': None},
      'monitor': False,
      'state': 'configured'}],
    'port': {'zt*:6600': 6600},
    'privileged': False,
    'hostname': '',
    'storage': 'zdb://hub.grid.tf:9900',
    'name': 'zrobot',
    'tags': ['zrobot'],
    'env': {'HOME': '/root', 'LANG': 'C.UTF-8', 'LC_ALL': 'C.UTF-8'},
    'cgroups': [['devices', 'corex']],
    'config': None},
   'root': '/mnt/containers/1',
   'pid': 397}},
 '2': {'cpu': 0.05519280258075815,
  'rss': 8212480,
  'vms': 300244992,
  'swap': 0,
  'container': {'arguments': {'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-minio-zerostor.flist',
    'mount': {'/mnt/storagepools/sp_zos-cache/filesystems/minio.67fd2bbe-9f42-4d0d-a417-c2081559ca44': '/minio_metadata'},
    'host_network': False,
    'identity': '',
    'nics': [{'type': 'default',
      'id': '',
      'hwaddr': '',
      'config': {'dhcp': False, 'cidr': '', 'gateway': '', 'dns': None},
      'monitor': False,
      'state': 'configured'}],
    'port': {'1024': 9000},
    'privileged': False,
    'hostname': '',
    'storage': 'zdb://hub.grid.tf:9900',
    'name': 'minio_67fd2bbe-9f42-4d0d-a417-c2081559ca44',
    'tags': ['minio_67fd2bbe-9f42-4d0d-a417-c2081559ca44'],
    'env': {'MINIO_ACCESS_KEY': 'minio_login',
     'MINIO_SECRET_KEY': 'minio_password',
     'MINIO_ZEROSTOR_META_DIR': '/minio_metadata',
     'MINIO_ZEROSTOR_META_PRIVKEY': ''},
    'cgroups': [['devices', 'corex']],
    'config': {}},
   'root': '/mnt/containers/2',
   'pid': 707}}}

```

- Here is the minio container running process
```python
In [6]:  minio_container = node.client.container.client(2)
In [9]: minio_container.process.list()
Out[9]: 
[{'pid': 1,
  'ppid': 0,
  'cmdline': '/coreX -hostname -unprivileged',
  'name': 'coreX',
  'createtime': 1537710599000,
  'cpu': {'guestnice': 0,
   'idle': 0,
   'iowait': 0,
   'irq': 0,
   'nice': 0,
   'softirq': 0,
   'steal': 0,
   'stolen': 0,
   'system': 7.06,
   'user': 8.37},
  'rss': 8212480,
  'vms': 300244992,
  'swap': 0,
  'rlimit': [{'resource': 0, 'soft': 2147483647, 'hard': 2147483647},
   {'resource': 1, 'soft': 2147483647, 'hard': 2147483647},
   {'resource': 2, 'soft': 2147483647, 'hard': 2147483647},
   {'resource': 3, 'soft': 8388608, 'hard': 2147483647},
   {'resource': 4, 'soft': 0, 'hard': 2147483647},
   {'resource': 5, 'soft': 2147483647, 'hard': 2147483647},
   {'resource': 6, 'soft': 15106, 'hard': 15106},
   {'resource': 7, 'soft': 65536, 'hard': 65536},
   {'resource': 8, 'soft': 65536, 'hard': 65536},
   {'resource': 9, 'soft': 2147483647, 'hard': 2147483647},
   {'resource': 10, 'soft': 2147483647, 'hard': 2147483647},
   {'resource': 11, 'soft': 15106, 'hard': 15106},
   {'resource': 12, 'soft': 819200, 'hard': 819200},
   {'resource': 13, 'soft': 0, 'hard': 0},
   {'resource': 14, 'soft': 0, 'hard': 0},
   {'resource': 15, 'soft': 2147483647, 'hard': 2147483647}],
  'ofd': 6}]


```

**Env**
- JS development
- 0-Robot dev
- 0-template dev
- farm: TLRE

**Comment by zaibon** [comment]
what is the output of the minio process ?
did you check that all the zerodb used by minio are accessible and have the proper namespace ?

**Comment by zaibon** [comment]
what is the output of the minio process ?
did you check that all the zerodb used by minio are accessible and have the proper namespace ?

**Comment by islamTaha12** [comment]
I update the ticket with the minio process. 

How could I check the zerodb used by the minio?

**Comment by serboctor** [comment]
@islamTaha12 it is in the data of the minio service

**Comment by islamTaha12** [comment]
Here is the s3 data 
```
root@c92065781906:/opt/var/data/zrobot/zrobot_data/github.com/threefoldtech/0-templates/s3/7029b5d99d/67fd2bbe-9f42-4d0d-a417-c2081559ca44# cat data.yaml 
dataShards: 16
farmerIyoOrg: tlre
mgmtNic:
    id: af78bf9436630e43
    ztClient: 42555bd716
minioLogin: minio_login
minioPassword: minio_password
minioUrl: ''
namespaces:
-   name: 591a6824-ecf0-4798-a236-1f73d104b510
    node: ac1f6b47a274
    url: http://10.147.20.6:6600
-   name: a62b425b-3f91-48a3-a041-a8b374c8ace2
    node: ac1f6b457ae0
    url: http://10.147.20.196:6600
nsPassword: 4cgv35n5l8wx8o1jdecaiu7ydvklkod9
parityShards: 4
shardSize: 2000
storageSize: 5
storageType: ssd
```

- From the minio vm I can ping the zdb nodes:
```python
In [36]: node.client.bash('ping -w 1 10.147.20.6').get()
Out[36]: 
STATE: 0 SUCCESS
STDOUT:
PING 10.147.20.6 (10.147.20.6): 56 data bytes
64 bytes from 10.147.20.6: seq=0 ttl=64 time=0.333 ms

--- 10.147.20.6 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.333/0.333/0.333 ms

STDERR:

DATA:
```


```
In [38]: node.client.bash('ping -w 1 10.147.20.196').get()
Out[38]: 
STATE: 0 SUCCESS
STDOUT:
PING 10.147.20.196 (10.147.20.196): 56 data bytes
64 bytes from 10.147.20.196: seq=0 ttl=63 time=1.042 ms

--- 10.147.20.196 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.042/1.042/1.042 ms

STDERR:

DATA:

```

**Comment by islamTaha12** [comment]
- mino vm data 
```
In [52]: node.client.bash('cat /var/cache/zrobot/data/github.com/threefoldtech/0-templates/minio/67fd2bbe-9f42-4d0d-a417-c2081559ca44/f432ac75-b6dc-4a1c-8550-f2a6b107e445/data.yaml').get()
Out[52]: 
STATE: 0 SUCCESS
STDOUT:
dataShard: 16
login: minio_login
metaPrivateKey: ''
namespace: 67fd2bbe-9f42-4d0d-a417-c2081559ca44
nsSecret: 4cgv35n5l8wx8o1jdecaiu7ydvklkod9
parityShard: 4
password: minio_password
privateKey: ''
zerodbs:
- 172.20.18.18:1034
- 172.20.18.26:1025
```

- minio vm can ping 172.20.18.18 and 172.20.18.26

- zdbd r running 
```bash
gig@MAN-DC01-H1209-ARC03:~$ redis-cli -h 172.20.18.18 -p 1034
172.20.18.18:1034> ping
PONG
172.20.18.18:1034> nslist
1) "default"
2) "67fd2bbe-9f42-4d0d-a417-c2081559ca44"

gig@MAN-DC01-H1209-ARC03:~$ redis-cli -h 172.20.18.26 -p 1025
172.20.18.26:1025> ping
PONG
172.20.18.26:1025> nslist
1) "default"
2) "67fd2bbe-9f42-4d0d-a417-c2081559ca44"


```

**Comment by zaibon** [comment]
I don't think you've seen the full config file. You cannot have only 2 namespaces when you have a data and parity of 16/4. 
Also, what is the output of the minio process ? I'm sure it will tell you it cannot reach some of the zerodb.

**Comment by islamTaha12** [comment]
@zaibon I accessed the node and here is the results:
- minio data
```bash
/var/cache/zrobot/data/github.com/threefoldtech/0-templates/minio/67fd2bbe-9f42-4d0d-a417-c2081559ca44/f432ac75-b6dc-4a1c-8550-f2a6b107e445 # cat data.yaml 
dataShard: 16
login: minio_login
metaPrivateKey: ''
namespace: 67fd2bbe-9f42-4d0d-a417-c2081559ca44
nsSecret: 4cgv35n5l8wx8o1jdecaiu7ydvklkod9
parityShard: 4
password: minio_password
privateKey: ''
zerodbs:
- 172.20.18.18:1034
- 172.20.18.26:1025
```

- minio process output:
```python
In [68]: r = node.client.response_for('minio.67fd2bbe-9f42-4d0d-a417-c2081559ca44')

In [69]: r.exists
Out[69]: True

In [70]: r.get()
Out[70]: 
STATE: 1001 ERROR
STDOUT:
zerostor config file =  /bin/zerostor.yaml
debugging flag:  false
metadata encrypted:  false
failed to creates zstor client:  DistributedChunkStorage requires at least dataShardCount+parityShardCount amount of listed datastor shards

Trace: 1: cmd/gateway-main.go:170:cmd.StartGateway()
       2: cmd/gateway/zerostor/gateway-zerostor.go:104:zerostor.zerostorGatewayMain()
       3: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: vendor/github.com/minio/cli/app.go:386:cli.(*App).RunAsSubcommand()
       6: vendor/github.com/minio/cli/command.go:302:cli.Command.startApp()
       7: vendor/github.com/minio/cli/command.go:100:cli.Command.Run()
       8: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       9: cmd/main.go:155:cmd.Main()
      10: main.go:71:main.main()
[2018-09-24T10:02:56.120197375Z] [FATAL] Unable to initialize gateway layer (DistributedChunkStorage requires at least dataShardCount+parityShardCount amount of listed datastor shards)

STDERR:

DATA:
```

zerostor config
```bash
/mnt/containers/2/bin # cat zerostor.yaml 
namespace: 67fd2bbe-9f42-4d0d-a417-c2081559ca44
password: 4cgv35n5l8wx8o1jdecaiu7ydvklkod9
datastor: # required
  shards: # required
    - 172.20.18.18:1034
    - 172.20.18.26:1025
  pipeline:
    block_size: 1048576
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: 
    distribution:
      data_shards: 16
      
/mnt/containers/2/bin # 
```

so when I created the s3 with default values ` dataShards @2: Int32=16; # 0-stor data shards config   parityShards @3: Int32=4; # 0-stor parity shards config`, minio config try to use only 2 namespaces.

**Comment by islamTaha12** [comment]
s3 creation data:
```
s3_data = {
    ...: ^I'farmerIyoOrg': 'tlre',
    ...: ^I'mgmtNic': {'id': 'af78bf9436630e43', 'ztClient': zerotier_client},
    ...: ^I'storageType': 'ssd',
    ...: ^I'storageSize': 5,
    ...: ^I'minioLogin': 'minio_login',
    ...: ^I'minioPassword': 'minio_password'
    ...: }

```

s3 services data
```
root@c92065781906:/opt/var/data/zrobot/zrobot_data/github.com/threefoldtech/0-templates/s3/7029b5d99d/67fd2bbe-9f42-4d0d-a417-c2081559ca44# cat data.yaml 
dataShards: 16
farmerIyoOrg: tlre
mgmtNic:
    id: af78bf9436630e43
    ztClient: 42555bd716
minioLogin: minio_login
minioPassword: minio_password
minioUrl: ''
namespaces:
-   name: 591a6824-ecf0-4798-a236-1f73d104b510
    node: ac1f6b47a274
    url: http://10.147.20.6:6600
-   name: a62b425b-3f91-48a3-a041-a8b374c8ace2
    node: ac1f6b457ae0
    url: http://10.147.20.196:6600
nsPassword: 4cgv35n5l8wx8o1jdecaiu7ydvklkod9
parityShards: 4
shardSize: 2000
storageSize: 5
storageType: ssd

```

**Comment by zaibon** [comment]
ok so I know the problem. you set a storageSize to 5 but you left the shard size to 2000. 
So when we compute the number of shards we have something wrong. See https://github.com/threefoldtech/0-templates/blob/0e5300a7a0d2651c6ee526c9df9c21c9d57217e4/templates/s3/s3.py#L348-L365

I'll add some checks in the validate method to prevent that.

**Comment by islamTaha12** [comment]
Have the same case with updated 0-template: 

- s3 data
```python
{'farmerIyoOrg': 'tlre',
 'mgmtNic': {'id': 'af78bf9436630e43', 'ztClient': '42555bd716'},
 'storageType': 'ssd',
 'storageSize': 2500,
 'minioLogin': 'minio_login',
 'minioPassword': 'minio_password'}
```

- s3 service data
```yml
dataShards: 16
farmerIyoOrg: tlre
mgmtNic:
    id: af78bf9436630e43
    ztClient: 42555bd716
minioLogin: minio_login
minioPassword: minio_password
minioUrl: ''
namespaces:
-   name: 0be2d12b-17d3-4400-964b-4a9a2c919ba7
    node: ac1f6b457ae0
    url: http://10.147.20.196:6600
-   name: c2d793d1-c8be-4433-99c0-527b39c2ae90
    node: ac1f6b457ce4
    url: http://10.147.20.34:6600
-   name: 034d457e-9381-4e6a-b538-fc1322bcc96b
    node: ac1f6b47a274
    url: http://10.147.20.6:6600
nsPassword: gyqn1zlxuqci9ick17phz6vtm1q55kf3
parityShards: 4
shardSize: 2000
storageSize: 2500
storageType: ssd
```

- minio data 
```yml
In [111]: node.client.bash('cat /var/cache/zrobot/data/github.com/threefoldtech/0-templates/minio/e8fca758-99fd-43ac-bc79-648bfe518e0a/75de1bad-eca9-44c3-a951-e94d2562b513/data.yaml').get()
Out[111]: 
STATE: 0 SUCCESS
STDOUT:
dataShard: 16
login: minio_login
metaPrivateKey: ''
namespace: e8fca758-99fd-43ac-bc79-648bfe518e0a
nsSecret: gyqn1zlxuqci9ick17phz6vtm1q55kf3
parityShard: 4
password: minio_password
privateKey: ''
zerodbs:
- 172.20.18.42:1025
- 172.20.18.26:1027
- 172.20.18.18:1041
```

- minio process output
```
In [126]: r = node.client.response_for('minio.e8fca758-99fd-43ac-bc79-648bfe518e0a')

In [127]: r.get()
Out[127]: 
STATE: 1001 ERROR
STDOUT:
zerostor config file =  /bin/zerostor.yaml
debugging flag:  false
metadata encrypted:  false
failed to creates zstor client:  DistributedChunkStorage requires at least dataShardCount+parityShardCount amount of listed datastor shards

Trace: 1: cmd/gateway-main.go:170:cmd.StartGateway()
       2: cmd/gateway/zerostor/gateway-zerostor.go:104:zerostor.zerostorGatewayMain()
       3: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       4: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       5: vendor/github.com/minio/cli/app.go:386:cli.(*App).RunAsSubcommand()
       6: vendor/github.com/minio/cli/command.go:302:cli.Command.startApp()
       7: vendor/github.com/minio/cli/command.go:100:cli.Command.Run()
       8: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       9: cmd/main.go:155:cmd.Main()
      10: main.go:71:main.main()
[2018-09-24T12:29:37.340134626Z] [FATAL] Unable to initialize gateway layer (DistributedChunkStorage requires at least dataShardCount+parityShardCount amount of listed datastor shards)

STDERR:

DATA:

```
