### ISSUE TITLE
S3: allow to configure tlog for metadata redundancy

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#130]
In order to enable metadata replication, minio needs to have an extra configuration section explained here: https://github.com/threefoldtech/minio/tree/zerostor-tlog/cmd/gateway/zerostor#transaction-log

when installing S3 template needs to also deploy a zerodb namespace in sequential mode on an SSD disk. The address of this namespace need to be set into the minio configuration as:
```yaml
minio:
  tlog:
    address: <ip>:<port>
    namespace: zdb namespace
    password: zdb namespace password
```

- [x] [update minio SAL to support tlog configuration](https://github.com/threefoldtech/jumpscale_lib/issues/153)
- [x] add required property/actions to minio template to support tlog configuration: https://github.com/threefoldtech/0-templates/commit/34180110284949240aa15043bd873d1fc1bee85b
- [ ] add logic into s3 template to deploy tlog namespace
