### ISSUE TITLE
After restarting tlog service for many times, Minio still point to an old one

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#179]
**Hint**
I had to do this scenario too many times to produce this bug

**Related test cases**
```
nosetests-3.4 -vs --logging-level=WARNING testcases/test_tlog.py
```

**Descriptions**
After restarting tlog service many times, Minio still point to an old one

**Steps**
- Restart tlog service many times 
- Check s3.minio_config 
- List namespaces under tlog zdb, It should match the one in s3.minio_config

**Actual Result**
```
In [49]: print(s3.minio_config)
namespace: namespace
password: 445t5b3gnx2ydkv1smjrvmflwu6s58pe
datastor: # required
  shards: # required
    - 10.102.234.243:1050
    - 10.102.114.69:1034
    - 10.102.178.130:1051
  pipeline:
    block_size: 1048576
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: 
    distribution:
      data_shards: 1
      parity_shards: 1
minio:
  tlog:
    address: 10.102.96.237:1044
    namespace: namespace_tlog
    password: 445t5b3gnx2ydkv1smjrvmflwu6s58pe
```

```
╭─xtremx@xtrem-x /opt/code/github/threefoldtech/minio  ‹failures_testsuite*› 
╰─$ redis-cli -h 10.102.96.237 -p 1044
10.102.96.237:1044> nslist
1) "default"
2) "ee49471d-fefe-4eea-9aca-3b7d0370e9a8"
10.102.96.237:1044> 
10.102.96.237:1044> nslist
1) "default"
2) "ee49471d-fefe-4eea-9aca-3b7d0370e9a8"
(0.69s)
10.102.96.237:1044> 


```

**Repos**
development
